"""remove repository id sequence

Revision ID: 4219195d7d8d
Revises: 489a226ebf0d
Create Date: 2026-09-01 22:56:32.335413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4219195d7d8d'
down_revision: Union[str, Sequence[str], None] = '489a226ebf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("repositories", "id", server_default=None)
    op.execute("DROP SEQUENCE IF EXISTS repositories_id_seq")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE IF NOT EXISTS repositories_id_seq")
    op.alter_column("repositories", "id", server_default=sa.text("nextval('repositories_id_seq'::regclass)"))
    # ### end Alembic commands ###
